variables:
  DOCKER_DRIVER: overlay

stages:
  - prepare_docker
  - test
  - package

services:
  - docker:dind

before_script:
  - git submodule update --init
  - ./make_deps.sh
  - rm -rf build && mkdir build && cd build
  - cmake -DCMAKE_INSTALL_PREFIX=/usr ..

#
# Prepare Docker images
#
prepare_docker:16.04:
  stage: prepare_docker
  image: docker:git
  before_script:
    - echo "Nothing to do"
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker build --pull -t $CI_REGISTRY_IMAGE:ci_16.04 -f $CI_PROJECT_DIR/ci/Dockerfile_16.04 .
    - docker push $CI_REGISTRY_IMAGE:ci_16.04

prepare_docker:18.04:
  stage: prepare_docker
  image: docker:git
  before_script:
    - echo "Nothing to do"
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker build --pull -t $CI_REGISTRY_IMAGE:ci_18.04 -f $CI_PROJECT_DIR/ci/Dockerfile_18.04 .
    - docker push $CI_REGISTRY_IMAGE:ci_18.04

#
# Tests
#
test:16.04:
  stage: test
  image: $CI_REGISTRY_IMAGE:ci_16.04
  script: 
    - make -j$(nproc)
    - make test

test:18.04:
  stage: test
  image: $CI_REGISTRY_IMAGE:ci_18.04
  script: 
    - make -j$(nproc)
    - make test

#
# Package
#
package:
  stage: package
  image: $CI_REGISTRY_IMAGE:ci_16.04
  script:
    - make -j$(nproc)
    - make package
    - mv *.deb ../
    - mv addons/blender/*.tar.bz2 ../
  only:
    - tags
  artifacts:
    name: "splash_${CI_BUILD_REF_NAME}"
    paths:
    - "*.deb"
    - "*.tar.bz2"

#
# Static analysis
#
static_analysis:
  stage: test
  image: $CI_REGISTRY_IMAGE:ci_16.04
  script:
    - wget https://scan.coverity.com/download/linux64 --post-data "token=zkRfEWYxyAeJDlYYg9Hkkg&project=paperManu%2Fsplash" -O coverity_tool.tgz
    - tar xvzf coverity_tool.tgz
    - $(ls | grep cov-analysis)/bin/cov-build --dir cov-int make -j$(nproc)
    - tar caf splash-cov.bz2 cov-int
    - curl --form token=zkRfEWYxyAeJDlYYg9Hkkg --form email=emmanueldurand@gmail.com --form file=@splash-cov.bz2 --form description="Splash" https://scan.coverity.com/builds?project=paperManu%2Fsplash
    - apt install -y libpcre3-dev
    - make static_analysis
    - mv tests/static_analysis_result.txt ../
  only:
    - static_analysis
  artifacts:
    name: "splash_static_analysis_${CI_BUILD_REF_NAME}"
    paths:
    - "static_analysis_result.txt"

