image: ubuntu:xenial

before_script: 
  - apt update -qq
  - apt install -y build-essential git-core zip subversion cmake libtool clang libxrandr-dev libxi-dev libglm-dev libgsl0-dev libatlas3-base libzmq3-dev libsnappy-dev libgphoto2-dev libglfw3-dev libxinerama-dev libxcursor-dev python3-dev portaudio19-dev yasm
  - git submodule update --init
  - ./make_deps.sh
  - rm -rf build && mkdir build && cd build
  - cmake ..

stages:
  - test
  - package

test:
  stage: test
  script: 
    - make -j$(nproc)
    - make test

package:
  stage: package
  script:
    - make -j$(nproc)
    - make package
  only:
    - tags
  artifacts:
    paths:
    - "build/*.deb"
