language: cpp
compiler: gcc

branches:
    - master
    - develop
    - coverity_scan

os : linux
dist: trusty
sudo: required

before_install:
    - echo $LANG
    - echo $LC_ALL
    - sudo apt-add-repository -y ppa:sat-metalab/metalab
    - sudo apt-add-repository -y ppa:andrewrk/rucksack
    - sudo apt-get update -qq
    - sudo apt-get install -y build-essential git-core subversion cmake libtool clang libxrandr-dev libxi-dev libglm-dev libgsl0-dev libatlas3-base libzmq3-dev libsnappy-dev libgphoto2-dev libglfw3-dev libxinerama-dev libxcursor-dev python3-dev libavformat-dev libavcodec-dev libavutil-dev libswscale-dev portaudio19-dev

before_script:
    - git submodule update --init

script: 
    - rm -rf build && mkdir build && cd build
    - cmake ..
    - if [ "${COVERITY_SCAN_BRANCH}" !=  1 ]; then make; make check; fi

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "OGeRK7zAmPVAkSzleYm51NRvpGLZF1b1y8sCWZA9bC2lpcXR9aEM7UNQp/Cx6UKT+uCj/sfBIwwxcBQqrWD/IwQ6GfO2Y9qEnuEZucifnxCT2x562zpqB8RDV396V0uZZPzn5NnVs9aIQt2AIObIOik5141Mkodk54mytIvEQ7pPrXn1BUSeE4j1+1EbfkYP+6S58KjNR+9gc9XHSn2Bdvw4QZYxViGIerS+W5UMbukLcO58e4PrWYlR+93TW8PnfgATKZrPG2rbs1pFIr/Tn2mnWkwIspGF/cYtVn8LYAdLHjv8TMXm+hVVU0PcWROBtradl4AM6soH4BeaeG44Y852CzkUpK4GyT3meazoW6TPFUJQ3VgbN1NHNounArtymdTbyXmR2fHRvFgzDkaXOHkPbNYspnzwPLdwW81aFy+2T+rrbroB5auUApCTEbjqK3KaEaosoxo6kpdJDqPVxc4HAxowJcF6hllI32kd5jPz4h1LR8qkKXtYo1+3DN3CHOd3MCD6JTt/O5GTHoCygWLhgFYmN7M6e01J3CAnGPi4BpdKVATcxlZdiFy+1IDxXIwG1HeTvRi+tjO9ZsaYe+Ev4R5RyjkaQYdrh9Eq8YZRDp/oGywlafBfIgvqIkuVpNXyYp9tMtKlsuesLplaq1xvd65gLqp+JYioAlsdpPM="

addons:
  coverity_scan:
    project:
      name: "paperManu/splash"
      description: "Build submitted via Travis CI"
    notification_email: emmanueldurand@gmail.com
    build_command_prepend: "rm -rf build; mkdir build; cd build; cmake .."
    build_command:   "make -j 4"
    branch_pattern: coverity_scan
