language: cpp
compiler: gcc

branches:
    - master
    - develop

os : linux
dist: trusty
sudo: required

before_install:
    - echo $LANG
    - echo $LC_ALL
    - sudo apt-add-repository -y ppa:irie/blender
    - sudo apt-add-repository -y ppa:sat-metalab/metalab
    - sudo apt-add-repository -y ppa:andrewrk/rucksack
    - sudo apt-get update -qq
    - sudo apt-get install -y build-essential git-core subversion cmake libtool clang libxrandr-dev libxi-dev libglm-dev libgsl0-dev libatlas3-base libzmq3-dev libsnappy-dev libgphoto2-dev libglfw3-dev libxinerama-dev libxcursor-dev python3-dev libavformat-dev libavcodec-dev libavutil-dev libswscale-dev portaudio19-dev

before_script:
    - git submodule update --init

script: 
    - mkdir build && cd build
    - cmake ..
    - make
